#!/bin/sh

absolutePath() {
  if [ -z "$1" ]; then
    echo Cannot get absolute path of empty file name 1>&2
    exit 1
  fi
  if [ -d "$1" ]; then
    (
      cd "$1" || exit
      pwd
    )
  elif [ -f "$1" ]; then
    (
      cd "$(dirname "$1")" || exit
      echo "$(pwd)/$(basename "$1")"
    )
  else
    echo Cannot get absolute path of "$1", not regular file or directory 1>&2
    exit 1
  fi
}

myName="$(absolutePath "$0")"
topDir="$(dirname "$0")"

# Determine which profile to use.
# .profile is not read if .bash_profile exists...
for profileBasename in .bash_profile .profile; do
  profile="$HOME"/"$profileBasename"
  if [ -e "$profile" ]; then
    break
  fi
done

if grep "Added by \$myName" "$profile"; then
  echo Already setup in "$profile"
else
  {
    echo
    echo \# Added by "$myName"
    echo . $/profile \""$topDir"\"
  } >>"$profile"
  echo "$profile" updated
fi
