#!/bin/sh

# Adds local profile to users home profile.

getAbsolutePath() {
  if [ -d "$1" ]
  then
    (cd "$1" || exit ; pwd)
  else
    (cd `dirname "$1"` || exit ; echo `pwd`/`basename "$1"`)
  fi
}

myName=`getAbsolutePath "$0"`
topDir=`dirname "$myName"`

# Determine which profile to use.
# .profile is not read if .bash_profile exists...
for profileBasename in .bash_profile .profile; do
  profile="$HOME"/"$profileBasename"
  if [ -f "$profile" ]; then
    break
  fi
done

if grep "Added by $myName" "$profile" > /dev/null
then
  echo Already setup in "$profile". To update, first manually delete lines in
  echo "$profile" that source "$topDir"/profile and then rerun $0.
else
  {
    echo
    echo \# Added by "$myName"
    echo . "$topDir"/profile \""$topDir"\"
  } >>"$profile"
  echo "$profile" updated
fi

for subDir in "$topDir"/*; do
  if [ -d "$subDir" ]; then
    if [ -f "$subDir"/setup ]; then
      . "$subDir"/setup
    fi
  fi
done
