#!/bin/sh

# Desc:Adds local profile to users home profile.
# Must be idempotent: don't fu(k it up if run multiple times.

# TODO - Create one bin directory with links to appropriate bin directories

# This script will be run on older systems that can't use these standard features.
# shellcheck disable=SC2046
# shellcheck disable=SC2006

getAbsolutePath() {
  if [ -d "$1" ]
  then
    (cd "$1" || exit ; pwd)
  else
    (cd `dirname "$1"` || exit ; echo `pwd`/`basename "$1"`)
  fi
}

myName=`getAbsolutePath "$0"`
topDir=`dirname "$myName"`

# Both profiles need to be checked since different systems use
# different profiles. Ksh uses .profile, bash uses .bash_profile.
utilsProfile="$topDir"/profile
for profileBasename in .bash_profile .profile
do
  profile="$HOME"/"$profileBasename"
  if grep "^\. $utilsProfile" "$profile" > /dev/null
  then
    echo "$utilsProfile" is already setup in "$profile". To update, first manually delete lines in
    echo "$profile that source $utilsProfile and then rerun $0."
  else
    {
      echo
      echo \# Added by "$myName" on `date`
      echo . "$utilsProfile" \""$topDir"\"
    } >>"$profile"
    echo "$utilsProfile added to $profile."
  fi
done

for subDir in "$topDir"/*; do
  if [ -d "$subDir" ]; then
    if [ -f "$subDir"/setup ]; then
      . "$subDir"/setup
    fi
  fi
done
