#!/bin/sh

getAbsolutePath()
{
	if [ -d "$1" ]
	then
		( cd "$1" ; `pwd` )
	else
		( cd `dirname "$1"` ; echo `pwd`/`basename "$1"` )
	fi
}

SELF=`getAbsolutePath "$0"`
MY_DIR=`dirname "$SELF"`

if [ -e ~/.vimrc ] 
then
	if [ -h ~/.vimrc ]
	then
		rm ~/.vimrc
	else
		echo ~/.vimrc exists and is not a synbolic link.
		exit
	fi
fi

ln -s "$MY_DIR"/unix/bin/dot-vimrc ~/.vimrc

