#!/bin/sh

# Desc:Adds dot-profile to users home profile.
# Must be idempotent: don't fu(k it up if run multiple times.

# TODO - Create one bin directory with links to appropriate bin directories

# This script will be run on older systems that can't use these standard features.
# shellcheck disable=SC2046
# shellcheck disable=SC2006

getAbsolutePath()
{
	if [ -d "$1" ]
	then
		# shellcheck disable=SC2164
		# shellcheck disable=SC2092
		( cd "$1" ; `pwd` )
	else
		# shellcheck disable=SC2164
		( cd `dirname "$1"` ; echo `pwd`/`basename "$1"` )
	fi
}

myName=`getAbsolutePath "$0"`
MY_DIR=`dirname "$myName"`

if [ -e ~/.vimrc ]
then
	if [ -h ~/.vimrc ]
	then
		rm ~/.vimrc
	else
		echo ~/.vimrc exists and is not a synbolic link.
		exit
	fi
fi

ln -s "$MY_DIR"/unix/bin/dot-vimrc ~/.vimrc
